import React, { useState } from 'react';
import { Zap, Activity, Brain, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';
import { simulateAttack, ATTACK_METADATA, trainModel, getModelStatus } from '../services';
import { useToast } from '../hooks/use-toast';
import { DEMO_MODE, DEMO_FORENSIC_REPORT, DEMO_ML_STATUS } from '../constants';

export default function AttackSimulator() {
  const { toast } = useToast();
  const [selectedAttack, setSelectedAttack] = useState('');
  const [simulating, setSimulating] = useState(false);
  const [training, setTraining] = useState(false);
  const [message, setMessage] = useState('');
  const [simulationResult, setSimulationResult] = useState(null);
  const [modelStatus, setModelStatus] = useState(null);

  const attacks = ATTACK_METADATA.map((meta) => ({
    id: meta.id,
    name: meta.name,
    description: meta.description,
    icon: meta.icon
  }));

  // Generate forensic data for this incident
  const generateForensicData = (attackType, sourceIp) => {
    const threatRecommendations = {
      bruteforce: [
        'Block source IP at firewall immediately',
        'Force password reset for targeted accounts',
        'Enable account lockout policy',
        'Implement multi-factor authentication',
        'Review all successful logins from this period',
      ],
      ddos: [
        'Enable rate limiting on affected services',
        'Activate CDN/DDoS protection',
        'Block attacking IP ranges at edge',
        'Scale infrastructure if possible',
        'Contact ISP for upstream filtering',
      ],
      sql_injection: [
        'Block source IP immediately',
        'Review database for unauthorized changes',
        'Check for data exfiltration',
        'Patch vulnerable application',
        'Implement Web Application Firewall rules',
      ],
      malware: [
        'Isolate affected host immediately',
        'Kill malicious process and quarantine files',
        'Run full antivirus/EDR scan',
        'Check for persistence mechanisms',
        'Scan network for lateral movement',
      ],
      exfiltration: [
        'Block destination IP and domain',
        'Identify scope of data potentially leaked',
        'Preserve logs for forensic analysis',
        'Notify security leadership immediately',
        'Prepare for breach disclosure',
      ],
      privilege_escalation: [
        'Revoke elevated privileges immediately',
        'Reset all affected user credentials',
        'Audit recent admin actions',
        'Check for unauthorized system changes',
        'Review sudo/admin group memberships',
      ],
    };

    return {
      summary: '', // Will be generated by Gemini
      system_info: {
        cpu_percent: Math.floor(Math.random() * 40) + 30,
        memory_percent: Math.floor(Math.random() * 30) + 50,
        memory_total_gb: 16.0,
        memory_available_gb: 5.1,
        disk_percent: 72.3,
        uptime_hours: Math.floor(Math.random() * 200) + 48,
      },
      processes: [
        { pid: 1234, name: 'cmd.exe', cpu_percent: 2.5, memory_percent: 15.2, status: 'running' },
        { pid: 5678, name: 'powershell.exe', cpu_percent: 8.1, memory_percent: 45.6, status: 'running' },
        { pid: Math.floor(Math.random() * 9000) + 1000, name: 'suspicious_proc.exe', cpu_percent: 15.2, memory_percent: 88.4, status: 'running' },
        { pid: 7890, name: 'svchost.exe', cpu_percent: 0.8, memory_percent: 8.2, status: 'running' },
      ],
      connections: [
        { local_address: `${sourceIp}:52341`, remote_address: '45.33.32.156:443', status: 'ESTABLISHED' },
        { local_address: `${sourceIp}:22`, remote_address: '10.0.0.55:49152', status: 'ESTABLISHED' },
        { local_address: `${sourceIp}:49200`, remote_address: '8.8.8.8:53', status: 'TIME_WAIT' },
      ],
      indicators: [
        `Attack Type: ${attackType.replace('_', ' ').toUpperCase()}`,
        `Source IP: ${sourceIp}`,
        'Suspicious process execution detected',
        'Outbound connection to known threat IP',
        `Severity: HIGH - Immediate action required`,
      ],
      recommendations: threatRecommendations[attackType] || threatRecommendations.malware,
    };
  };

  // DEMO MODE: Create incident locally with forensic data
  const createDemoIncident = (attackType) => {
    const attackMeta = ATTACK_METADATA.find(m => m.id === attackType) || { name: attackType };
    const sourceIp = '192.168.1.' + Math.floor(Math.random() * 255);
    const forensics = generateForensicData(attackType, sourceIp);
    
    const incident = {
      id: Date.now(),
      type: attackType,
      threat_type: attackType,
      title: `${attackMeta.name} Attack Detected`,
      description: `Simulated ${attackMeta.name} attack from Attack Simulator`,
      severity: ['critical', 'high'][Math.floor(Math.random() * 2)],
      status: 'open',
      source_ip: sourceIp,
      timestamp: new Date().toISOString(),
      created_at: new Date().toISOString(),
      ml_flagged: true,
      confidence: (Math.random() * 0.2 + 0.8).toFixed(2),
      forensics: forensics,
    };
    
    // Store in localStorage
    const stored = JSON.parse(localStorage.getItem('arc_demo_incidents') || '[]');
    stored.unshift(incident);
    localStorage.setItem('arc_demo_incidents', JSON.stringify(stored.slice(0, 50)));
    
    // Also create events
    const events = [];
    const eventCount = Math.floor(Math.random() * 10) + 5;
    for (let i = 0; i < eventCount; i++) {
      events.push({
        id: Date.now() + i,
        type: attackType,
        event_type: attackType,
        source_ip: sourceIp,
        severity: incident.severity,
        timestamp: new Date(Date.now() - i * 1000).toISOString(),
        created_at: new Date(Date.now() - i * 1000).toISOString(),
        details: { incident_id: incident.id, step: i + 1 },
      });
    }
    const storedEvents = JSON.parse(localStorage.getItem('arc_demo_events') || '[]');
    localStorage.setItem('arc_demo_events', JSON.stringify([...events, ...storedEvents].slice(0, 100)));
    
    return {
      success: true,
      attack_type: attackType,
      chain_length: eventCount,
      events_generated: eventCount,
      incident_created: true,
      incident_id: incident.id,
      ml_flagged: true,
    };
  };

  const handleSimulate = async () => {
    if (!selectedAttack) return;
    setSimulating(true);
    setMessage('');
    setSimulationResult(null);
    
    // DEMO MODE: Create incident locally
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 800)); // Simulate delay
      const result = createDemoIncident(selectedAttack);
      const attackName = ATTACK_METADATA.find(m => m.id === selectedAttack)?.name || selectedAttack;
      setMessage(`✅ ${attackName} simulation completed`);
      setSimulationResult(result);
      toast({
        title: 'Simulation Complete',
        description: `${result.chain_length} events generated, incident created`,
      });
      setSimulating(false);
      return;
    }
    
    try {
      const result = await simulateAttack(selectedAttack, '192.168.1.100');
      
      if (!result.error) {
        const attackName = ATTACK_METADATA[selectedAttack]?.name || selectedAttack;
        setMessage(`✅ ${attackName} simulation completed`);
        setSimulationResult(result);
        
        toast({
          title: 'Simulation Complete',
          description: `${result.chain_length || 0} events generated${result.incident_created ? ', incident created' : ''}`,
        });
      } else {
        setMessage(`❌ ${result.message}`);
        toast({
          title: 'Simulation Failed',
          description: result.message,
          variant: 'destructive',
        });
      }
    } catch (err) {
      setMessage('❌ Simulation failed');
      toast({
        title: 'Error',
        description: 'Failed to execute simulation',
        variant: 'destructive',
      });
    } finally {
      setSimulating(false);
    }
  };

  const handleTrain = async () => {
    setTraining(true);
    setMessage('');
    
    // DEMO MODE: Simulate training
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate training time
      const result = {
        ...DEMO_ML_STATUS,
        samples: DEMO_ML_STATUS.samples + Math.floor(Math.random() * 100),
        message: 'Model trained successfully',
      };
      setMessage(`✅ ML model trained with ${result.samples} samples`);
      setModelStatus(result);
      toast({
        title: 'Training Complete',
        description: `Model trained on ${result.samples} samples`,
      });
      setTraining(false);
      return;
    }
    
    try {
      const result = await trainModel();
      
      if (!result.error) {
        setMessage(`✅ ML model trained with ${result.samples || 0} samples`);
        setModelStatus(result);
        
        toast({
          title: 'Training Complete',
          description: `Model trained on ${result.samples} samples`,
        });
      } else {
        setMessage(`❌ ${result.message}`);
        toast({
          title: 'Training Failed',
          description: result.message,
          variant: 'destructive',
        });
      }
    } catch (err) {
      setMessage('❌ Training failed');
      toast({
        title: 'Error',
        description: 'Failed to train model',
        variant: 'destructive',
      });
    } finally {
      setTraining(false);
    }
  };

  const handleCheckStatus = async () => {
    // DEMO MODE: Return hardcoded status
    if (DEMO_MODE) {
      setModelStatus(DEMO_ML_STATUS);
      return;
    }
    
    try {
      const status = await getModelStatus();
      if (!status.error) {
        setModelStatus(status);
      }
    } catch (err) {
      console.error('Failed to get model status:', err);
    }
  };

  return (
    <div className="p-8 space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">Attack Simulator</h1>
        <p className="text-gray-400">Simulate security attacks and train ML detection models</p>
      </div>

      {/* ML Training */}
      <div className="bg-gradient-to-br from-purple-500/10 to-blue-500/10 border border-purple-500/30 rounded-xl p-6">
        <div className="flex items-start justify-between">
          <div className="flex items-center space-x-4">
            <div className="w-12 h-12 bg-purple-500/20 rounded-lg flex items-center justify-center">
              <Brain className="w-6 h-6 text-purple-400" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white mb-1">ML Model Training</h2>
              <p className="text-sm text-gray-400">Train Isolation Forest model on baseline telemetry data</p>
              {modelStatus && !modelStatus.error && (
                <div className="flex items-center space-x-4 mt-2 text-xs">
                  <span className="text-green-400">
                    <CheckCircle className="w-3 h-3 inline mr-1" />
                    {modelStatus.trained ? 'Trained' : 'Not trained'}
                  </span>
                  {modelStatus.samples && (
                    <span className="text-gray-400">{modelStatus.samples} samples</span>
                  )}
                </div>
              )}
            </div>
          </div>
          <div className="flex space-x-2">
            <button
              onClick={handleCheckStatus}
              className="px-4 py-3 bg-[#1e293b] text-gray-400 rounded-lg hover:bg-[#2d3748] transition-all text-sm"
            >
              Check Status
            </button>
            <button
              data-testid="train-ml-button"
              onClick={handleTrain}
              disabled={training}
              className="flex items-center space-x-2 px-6 py-3 bg-purple-500/10 text-purple-400 border border-purple-500/30 rounded-lg hover:bg-purple-500/20 transition-all disabled:opacity-50"
            >
              <Activity className={`w-5 h-5 ${training ? 'animate-pulse' : ''}`} />
              <span>{training ? 'Training...' : 'Train Model'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Attack Simulations */}
      <div>
        <h2 className="text-xl font-bold text-white mb-4">Select Attack Type</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {attacks.map((attack) => (
            <button
              key={attack.id}
              data-testid={`attack-${attack.id}`}
              onClick={() => setSelectedAttack(attack.id)}
              className={`text-left bg-[#0f1419] border rounded-xl p-6 transition-all ${
                selectedAttack === attack.id
                  ? 'border-cyan-500/50 bg-cyan-500/5'
                  : 'border-[#1e293b] hover:border-cyan-500/30'
              }`}
            >
              <div className="text-3xl mb-3">{attack.icon}</div>
              <h3 className="text-lg font-bold text-white mb-2">{attack.name}</h3>
              <p className="text-sm text-gray-400">{attack.description}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Execute Button and Results */}
      <div className="space-y-4">
        <div className="flex items-center space-x-4">
          <button
            data-testid="simulate-button"
            onClick={handleSimulate}
            disabled={!selectedAttack || simulating}
            className="flex items-center space-x-3 px-8 py-4 bg-gradient-to-r from-red-500/20 to-orange-500/20 text-orange-400 border border-orange-500/30 rounded-xl hover:from-red-500/30 hover:to-orange-500/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Zap className={`w-5 h-5 ${simulating ? 'animate-pulse' : ''}`} />
            <span className="font-semibold">{simulating ? 'Simulating...' : 'Execute Simulation'}</span>
          </button>
          {message && (
            <div data-testid="simulation-message" className="text-sm text-gray-300 bg-[#0f1419] border border-[#2d3748] px-4 py-3 rounded-lg">
              {message}
            </div>
          )}
        </div>

        {/* Simulation Results */}
        {simulationResult && !simulationResult.error && (
          <div className="bg-[#0f1419] border border-[#1e293b] rounded-xl p-6">
            <h3 className="text-lg font-bold text-white mb-4">Simulation Results</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-[#1a1f2e] rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-cyan-400">{simulationResult.chain_length || 0}</div>
                <div className="text-xs text-gray-400 mt-1">Events Generated</div>
              </div>
              <div className="bg-[#1a1f2e] rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-white">{simulationResult.attack_type || '-'}</div>
                <div className="text-xs text-gray-400 mt-1">Attack Type</div>
              </div>
              <div className="bg-[#1a1f2e] rounded-lg p-4 text-center">
                {simulationResult.incident_created ? (
                  <CheckCircle className="w-8 h-8 text-green-400 mx-auto" />
                ) : (
                  <XCircle className="w-8 h-8 text-gray-500 mx-auto" />
                )}
                <div className="text-xs text-gray-400 mt-1">Incident Created</div>
              </div>
              <div className="bg-[#1a1f2e] rounded-lg p-4 text-center">
                {simulationResult.ml_flagged ? (
                  <AlertTriangle className="w-8 h-8 text-yellow-400 mx-auto" />
                ) : (
                  <CheckCircle className="w-8 h-8 text-gray-500 mx-auto" />
                )}
                <div className="text-xs text-gray-400 mt-1">ML Flagged</div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
